version: "3.8"

services:
  backend:
    build: .
    container_name: exp
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
